# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('cost', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=200)),
                ('sells', models.BooleanField(default=False)),
            ],
        ),
    ]
