# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='kek', max_length=200),
            preserve_default=False,
        ),
    ]
