# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20170119_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='count',
            field=models.IntegerField(),
        ),
    ]
