# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20170119_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='image_1',
            field=models.ImageField(default='kek', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_10',
            field=models.ImageField(default='kek', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(default='kek', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(default='kek', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(default='kek', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_5',
            field=models.ImageField(default='kek', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_6',
            field=models.ImageField(default='kek', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_7',
            field=models.ImageField(default='kek', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_8',
            field=models.ImageField(default='kek', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_9',
            field=models.ImageField(default='kek', upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
