# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20170119_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_1',
        ),
    ]
