# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20170329_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(0, 'Puma'), (1, 'Adidas'), (2, 'Nike')], default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
