# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_product_image_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_10',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_7',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_8',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_9',
        ),
    ]
